# Generated by Django 4.1.3 on 2022-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_autor_post_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
